#!/bin/bash

## -----------------------------------------
## Import laravel/homestead to local project
## -----------------------------------------
#`which composer` require laravel/homestead

## -----------------------------------------
## Initialize Homestead setup
## -----------------------------------------
#which php | vendor/bin/homestead make

## -------------------------------------------------------
## Modify app name from homestead.app to reorgresearch.app
## -------------------------------------------------------
sed -i.yaml 's/homestead.app/reorgresearch.app/g' Homestead.yaml

## -----------------------------------------------
## Modify DB name from homestead to reorgresearch.
## -----------------------------------------------
sed -i.yaml 's/- homestead/- reorgresearch/g' Homestead.yaml

## ------------------------------------
## Remove backup file generated by sed
## ------------------------------------
rm Homestead.yaml.yaml

## -----------------------------------------
## Bootup Vagrant machine
## -----------------------------------------
#vagrant up

## -----------------------------------------
## SSH into Vagrant machine
## -----------------------------------------
#vagrant ssh ; cd reorgresearch